name: Regression Suite

on:
  workflow_dispatch:
    inputs:
      test_cases:
        description: 'Test cases to run (e.g., LoginTests#testLogin+testLogout,SignupTests#testSignup)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'


      - name: Run selected test cases
        continue-on-error: true
        run: |
          echo "Running the following test cases:"
          echo "${{ github.event.inputs.test_cases }}"
          mvn -Dtest="${{ github.event.inputs.test_cases }}" test

      - name: Checkout GitHub Pages branch
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_report: allure-report
          gh_pages: gh-pages
          allure_history: allure-history
          retention_period: 5

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

      - name: Send Email
        uses: hilarion5/send-mail@v1
        with:
          smtp-server: smtp.gmail.com
          smtp-port: 465
          smtp-secure: true
          from-email: harshhpatel07@gmail.com
          to-email: harshvegada1997@gmail.com,write2technocredits@gmail.com
          username: harshhpatel07@gmail.com
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Test Email
          content_type: text/html
          body: |
            <p>The Allure report for the latest run in <strong>${{ github.repository }}</strong> is available at:</p>
            <p><a href="https://harshvegada.github.io/MAY25_HRM_API/${{ github.run_number }}">View Report</a></p>
